In [1]:
import pandas as pd
import numpy as np

In [124]:
enroll = pd.read_csv("enrolment-by-institutions.csv", index_col = ["year", "sex"], na_values = "-")
enroll = enroll.fillna(0)
enroll

            nus    ntu     smu     sit    sutd    suss   nie  \
year sex
1982 MF   11093    582     0.0     0.0     0.0     0.0  1000
     F     5563     57     0.0     0.0     0.0     0.0   808
1983 MF   11939   1267     0.0     0.0     0.0     0.0  1078
     F     6596    120     0.0     0.0     0.0     0.0   853
1984 MF   12721   1945     0.0     0.0     0.0     0.0   776
     F     7076    230     0.0     0.0     0.0     0.0   605
1985 MF   13617   2078     0.0     0.0     0.0     0.0  1166
     F     7396    253     0.0     0.0     0.0     0.0   922
1986 MF   14150   2202     0.0     0.0     0.0     0.0  1331
     F     7581    302     0.0     0.0     0.0     0.0  1093
1987 MF   13238   3940     0.0     0.0     0.0     0.0  1306
     F     6822   1486     0.0     0.0     0.0     0.0  1085
1988 MF   14317   4400     0.0     0.0     0.0     0.0  1058
     F     7490   1750     0.0     0.0     0.0     0.0   849
1989 MF   14645   5475     0.0     0.0     0.0     0.0  1337
     F     7857   2123     0.0     0.0     0.0     0.0  1032
1990 MF   15193   6812     0.0     0.0     0.0     0.0  1577
     F     8107   2689     0.0     0.0     0.0     0.0  1212
1991 MF   14597   8712     0.0     0.0     0.0     0.0  1676
     F     7972   3139     0.0     0.0     0.0     0.0  1336
1992 MF   14922   9900     0.0     0.0     0.0     0.0  1559
     F     8096   3543     0.0     0.0     0.0     0.0  1189
1993 MF   15395  10410     0.0     0.0     0.0     0.0  1700
     F     8276   3802     0.0     0.0     0.0     0.0  1287
1994 MF   16137  11052     0.0     0.0     0.0     0.0  1394
     F     8644   4220     0.0     0.0     0.0     0.0  1019
1995 MF   16984  11545     0.0     0.0     0.0     0.0  1341
     F     9172   4741     0.0     0.0     0.0     0.0   997
1996 MF   17669  12186     0.0     0.0     0.0     0.0  2040
     F     9663   5030     0.0     0.0     0.0     0.0  1507
...         ...    ...     ...     ...     ...     ...   ...
2004 MF   21781  16837  3010.0     0.0     0.0     0.0  2282
     F    11372   7469  1991.0     0.0     0.0     0.0  1550
2005 MF   22105  17777  3781.0     0.0     0.0     0.0  2881
     F    11326   8094  2239.0     0.0     0.0     0.0  1940
2006 MF   22836  19114  4259.0     0.0     0.0     0.0  2938
     F    11766   8797  2429.0     0.0     0.0     0.0  1998
2007 MF   23578  20206  5178.0     0.0     0.0     0.0  2725
     F    12396   9769  2758.0     0.0     0.0     0.0  1878
2008 MF   24086  21097  5721.0     0.0     0.0     0.0  2581
     F    12663  10409  2993.0     0.0     0.0     0.0  1758
2009 MF   24798  22450  6331.0     0.0     0.0     0.0  2804
     F    12944  11105  3295.0     0.0     0.0     0.0  1896
2010 MF   25189  22862  6721.0   523.0     0.0     0.0  2816
     F    13067  11389  3525.0   275.0     0.0     0.0  1886
2011 MF   25513  23040  6853.0  1416.0     0.0     0.0  2579
     F    13066  11354  3523.0   732.0     0.0     0.0  1759
2012 MF   25979  22862  7108.0  2587.0   327.0     0.0  2445
     F    13295  11386  3684.0  1246.0   149.0     0.0  1624
2013 MF   26156  22777  7297.0  3051.0   583.0     0.0  1838
     F    13532  11517  3789.0  1317.0   249.0     0.0  1216
2014 MF   26797  23021  7515.0  3557.0   886.0   217.0  1913
     F    14042  11623  3883.0  1482.0   363.0   145.0  1313
2015 MF   27288  23512  7740.0  4039.0  1235.0   489.0  1549
     F    14423  11860  4062.0  1693.0   522.0   330.0  1015
2016 MF   27702  23495  7827.0  5230.0  1381.0   896.0  1443
     F    14617  11633  4047.0  2306.0   551.0   609.0  1010
2017 MF   28134  22934  7979.0  6138.0  1545.0  1451.0  1122
     F    14600  11079  4193.0  2626.0   603.0  1011.0   804
2018 MF   29037  22813  8182.0  6951.0  1658.0  2049.0  1309
     F    14981  10896  4486.0  2905.0   626.0  1399.0   924

          singapore_polytechnic  ngee_ann_polytechnic  temasek_polytechnic  \
year sex
1982 MF                    5339                  3660                  0.0
     F                     1069                  1153                  0.0
1983 MF                    6136                  4825                  0.0
     F                     1318                  1650                  0.0
1984 MF                    7129                  6919                  0.0
     F                     1679                  2374                  0.0
1985 MF                    7894                  8516                  0.0
     F                     1924                  2993                  0.0
1986 MF                    8099                  9617                  0.0
     F                     2041                  3470                  0.0
1987 MF                    9193                 10237                  0.0
     F                     2514                  3910                  0.0
1988 MF                    9709                 10448                  0.0
     F                     2905                  4037                  0.0
1989 MF                   10620                 11341                  0.0
     F                     3459                  4477                  0.0
1990 MF                   11348                 11995                735.0
     F                     3878                  4817                552.0
1991 MF                   12327                 12759               1472.0
     F                     4498                  5316               1006.0
1992 MF                   13257                 13330               2268.0
     F                     5073                  5527               1490.0
1993 MF                   13578                 13353               3107.0
     F                     5297                  5473               1826.0
1994 MF                   13865                 13637               3854.0
     F                     5361                  5624               2156.0
1995 MF                   14019                 14249               5443.0
     F                     5202                  5858               3026.0
1996 MF                   13912                 14480               7681.0
     F                     5180                  6113               4076.0
...                         ...                   ...                  ...
2004 MF                   13709                 13417              12782.0
     F                     5233                  6347               6302.0
2005 MF                   13353                 13715              13582.0
     F                     5019                  6500               6776.0
2006 MF                   13656                 14258              14568.0
     F                     5084                  6719               7236.0
2007 MF                   14399                 14687              15243.0
     F                     5249                  7007               7541.0
2008 MF                   14986                 15123              15615.0
     F                     5605                  7214               7587.0
2009 MF                   15523                 15417              15791.0
     F                     6034                  7436               7676.0
2010 MF                   15928                 15942              15933.0
     F                     6453                  7655               7804.0
2011 MF                   15949                 16139              16020.0
     F                     6432                  7703               7894.0
2012 MF                   15972                 16430              16005.0
     F                     6327                  7788               7855.0
2013 MF                   15878                 16581              16250.0
     F                     6167                  7866               7934.0
2014 MF                   15905                 16227              16138.0
     F                     6175                  7758               7900.0
2015 MF                   15297                 15611              15425.0
     F                     6022                  7465               7585.0
2016 MF                   14671                 14866              14662.0
     F                     5766                  7243               7115.0
2017 MF                   14298                 14599              14239.0
     F                     5611                  7304               6802.0
2018 MF                   14337                 14543              14248.0
     F                     5559                  7469               6688.0

          nanyang_polytechnic  republic_polytechnic  lasalle_diploma  \
year sex
1982 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1983 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1984 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1985 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1986 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1987 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1988 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1989 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1990 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1991 MF                   0.0                   0.0              0.0
     F                    0.0                   0.0              0.0
1992 MF                 699.0                   0.0              0.0
     F                  580.0                   0.0              0.0
1993 MF                3944.0                   0.0              0.0
     F                 1946.0                   0.0              0.0
1994 MF                5785.0                   0.0              0.0
     F                 3199.0                   0.0              0.0
1995 MF                7291.0                   0.0              0.0
     F                 4066.0                   0.0              0.0
1996 MF                7764.0                   0.0              0.0
     F                 4381.0                   0.0              0.0
...                       ...                   ...              ...
2004 MF               14233.0                1907.0              0.0
     F                 7875.0                 865.0              0.0
2005 MF               14643.0                3587.0           1505.0
     F                 8010.0                1759.0            906.0
2006 MF               15001.0                5479.0           1904.0
     F                 7913.0                2790.0           1139.0
2007 MF               14874.0                8087.0           1948.0
     F                 7732.0                4205.0           1228.0
2008 MF               15225.0               10188.0           1887.0
     F                 7866.0                5257.0           1202.0
2009 MF               15656.0               12179.0           1771.0
     F                 8150.0                6304.0           1143.0
2010 MF               16183.0               13003.0           1754.0
     F                 8387.0                6729.0           1137.0
2011 MF               16408.0               13927.0           1623.0
     F                 8440.0                7209.0           1011.0
2012 MF               16076.0               14520.0           1353.0
     F                 8197.0                7583.0            854.0
2013 MF               16266.0               14995.0           1253.0
     F                 8242.0                7910.0            769.0
2014 MF               16092.0               14952.0           1190.0
     F                 8189.0                7914.0            773.0
2015 MF               15842.0               14690.0           1173.0
     F                 8177.0                7736.0            765.0
2016 MF               15035.0               13915.0           1150.0
     F                 7661.0                7343.0            741.0
2017 MF               14734.0               13566.0           1241.0
     F                 7398.0                7022.0            783.0
2018 MF               14715.0               13142.0           1294.0
     F                 7304.0                6703.0            842.0

          lasalle_degree  nafa_diploma  nafa_degree    ite
year sex
1982 MF              0.0           0.0          0.0  10303
     F               0.0           0.0          0.0   2130
1983 MF              0.0           0.0          0.0  10664
     F               0.0           0.0          0.0   2753
1984 MF              0.0           0.0          0.0   9419
     F               0.0           0.0          0.0   2831
1985 MF              0.0           0.0          0.0  13890
     F               0.0           0.0          0.0   3839
1986 MF              0.0           0.0          0.0  14666
     F               0.0           0.0          0.0   4682
1987 MF              0.0           0.0          0.0  16539
     F               0.0           0.0          0.0   5601
1988 MF              0.0           0.0          0.0  17643
     F               0.0           0.0          0.0   5627
1989 MF              0.0           0.0          0.0  17353
     F               0.0           0.0          0.0   5751
1990 MF              0.0           0.0          0.0  15919
     F               0.0           0.0          0.0   5304
1991 MF              0.0           0.0          0.0  15326
     F               0.0           0.0          0.0   5172
1992 MF              0.0           0.0          0.0  14975
     F               0.0           0.0          0.0   4942
1993 MF              0.0           0.0          0.0  14903
     F               0.0           0.0          0.0   4625
1994 MF              0.0           0.0          0.0  12254
     F               0.0           0.0          0.0   3649
1995 MF              0.0           0.0          0.0   9300
     F               0.0           0.0          0.0   2726
1996 MF              0.0           0.0          0.0   8266
     F               0.0           0.0          0.0   2227
...                  ...           ...          ...    ...
2004 MF              0.0           0.0          0.0  19207
     F               0.0           0.0          0.0   6076
2005 MF              0.0        1933.0          0.0  21603
     F               0.0        1236.0          0.0   7315
2006 MF              0.0        2083.0          0.0  23636
     F               0.0        1352.0          0.0   8052
2007 MF              0.0        2114.0          0.0  24370
     F               0.0        1396.0          0.0   8235
2008 MF              0.0        2190.0          0.0  24593
     F               0.0        1475.0          0.0   8479
2009 MF              0.0        2144.0          0.0  24846
     F               0.0        1460.0          0.0   8844
2010 MF              0.0        2269.0          0.0  24789
     F               0.0        1532.0          0.0   8856
2011 MF              0.0        2217.0         20.0  25279
     F               0.0        1510.0          9.0   9158
2012 MF           1081.0        2225.0         43.0  25370
     F             771.0        1531.0         22.0   9085
2013 MF           1290.0        2037.0         51.0  26288
     F             956.0        1419.0         25.0   9428
2014 MF           1176.0        2022.0         53.0  28036
     F             846.0        1440.0         31.0  10249
2015 MF           1262.0        2106.0         59.0  29295
     F             905.0        1483.0         40.0  11267
2016 MF           1311.0        2390.0         50.0  27519
     F             946.0        1745.0         31.0  10346
2017 MF           1330.0        2537.0         39.0  28508
     F             987.0        1830.0         24.0  10804
2018 MF           1339.0        2484.0         43.0  28367
     F             981.0        1785.0         28.0  10707

[74 rows x 17 columns]

In [35]:
for i in range(len(enroll)):
    if enroll.index[i][0] == enroll.index[i+1][0]:
        print(enroll.nus[i] - enroll.nus[i+1])

5530 0
5343 2
5645 4
6221 6
6569 8
6416 10
6827 12
6788 14
7086 16
6625 18
6826 20
7119 22
7493 24
7812 26
8006 28
8111 30
8465 32
9059 34
9892 36
10391 38
10516 40
11113 42
10409 44
10779 46
11070 48
11182 50
11423 52
11854 54
12122 56
12447 58
12684 60
12624 62
12755 64
12865 66
13085 68
13534 70
14056 72

IndexError: index 74 is out of bounds for axis 0 with size 74

In [121]:
col = enroll.columns

for value in col:
    if enroll[value].dtype != "int64":
        enroll[value] = enroll[value].astype(int)
    else:
        pass